os: linux
dist: bionic

language: node_js
node_js:
    - 13

before_script: |-4
    # Script: `before_script`

    # Codecov
    npm install -g codecov

script: |-4
    # Script: `script`

    # Tests with coverage report
    npm run test:coverage

after_success: |-4
    # Script: `after_success`

    # Codecov
    npx codecov

before_deploy: |-4
    # Script: `before_deploy`

    # Build the web app
    npm run build:deploy

deploy:
    edge: true
    provider: pages
    token: $GITHUB_DEPLOY_TOKEN
    fqdn: 2047.jasonhk.app
    local_dir: dist
    allow_empty_commit: true
    cleanup: false
    on:
        node_js: 13
        branch: master
